// <auto-generated />
namespace Infopulse.EDemocracy.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class auth_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(auth_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201510261905366_auth_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
