//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infopulse.EDemocracy.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infopulse.EDemocracy.Common.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -21.
        /// </summary>
        public static string DbConnectionFailedCode {
            get {
                return ResourceManager.GetString("DbConnectionFailedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте, на разі база данних не доступна..
        /// </summary>
        public static string DbConnectionFailedMessage {
            get {
                return ResourceManager.GetString("DbConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка! Не можу виконати операцію. Якщо проблема повториться, зв&apos;яжіться, будь ласка, з адміністратором..
        /// </summary>
        public static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви вже проголосували за цю петицію..
        /// </summary>
        public static string PetitionAlreadyVotedException {
            get {
                return ResourceManager.GetString("PetitionAlreadyVotedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Петиція не знайдена..
        /// </summary>
        public static string PetitionNofFoundException {
            get {
                return ResourceManager.GetString("PetitionNofFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш голос чекає підтвердження. Перевірте вашу поштову скриньку {0}..
        /// </summary>
        public static string PetitionVoteNotConfirmedException_Mask {
            get {
                return ResourceManager.GetString("PetitionVoteNotConfirmedException_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -13.
        /// </summary>
        public static string SendEmailFailedCode {
            get {
                return ResourceManager.GetString("SendEmailFailedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Під час спроби відправити листа сталася помилка. Перевірте правильність вказаного вами email&apos;а і спробуйте ще раз..
        /// </summary>
        public static string SendEmailFailedMessage {
            get {
                return ResourceManager.GetString("SendEmailFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можу створити петицію через внутрішню помилку..
        /// </summary>
        public static string UnableToReadPetitionException {
            get {
                return ResourceManager.GetString("UnableToReadPetitionException", resourceCulture);
            }
        }
    }
}
