//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infopulse.EDemocracy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgreementVote
    {
        public long ID { get; set; }
        public long AgreementID { get; set; }
        public long PersonID { get; set; }
        public long CertificateID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string SignedData { get; set; }
        public string SignedHash { get; set; }
    
        public virtual Agreement Agreement { get; set; }
        public virtual Certificate Certificate { get; set; }
        public virtual Person Person { get; set; }
    }
}
