//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infopulse.EDemocracy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public Certificate()
        {
            this.AgreementVotes = new HashSet<AgreementVote>();
            this.PetitionVotes = new HashSet<PetitionVote>();
        }
    
        public long ID { get; set; }
        public long TypeID { get; set; }
        public long PersonID { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual ICollection<AgreementVote> AgreementVotes { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<PetitionVote> PetitionVotes { get; set; }
    }
}
