//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infopulse.EDemocracy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactGroup
    {
        public long ID { get; set; }
        public long GroupID { get; set; }
        public long ContactTypeID { get; set; }
        public long StatusID { get; set; }
        public string Value { get; set; }
    
        public virtual Entity ContactType { get; set; }
        public virtual Entity Status { get; set; }
        public virtual Group Group { get; set; }
    }
}
