//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infopulse.EDemocracy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityGroup
    {
        public EntityGroup()
        {
            this.Entities = new HashSet<Entity>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Entity> Entities { get; set; }
    }
}
