//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infopulse.EDemocracy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public Entity()
        {
            this.C_Invitation = new HashSet<C_Invitation>();
            this.C_Invitation1 = new HashSet<C_Invitation>();
            this.Agreements = new HashSet<Agreement>();
            this.Candidates = new HashSet<Candidate>();
            this.Candidates1 = new HashSet<Candidate>();
            this.Certificates = new HashSet<Certificate>();
            this.Contacts = new HashSet<Contact>();
            this.Contacts1 = new HashSet<Contact>();
            this.ContactGroups = new HashSet<ContactGroup>();
            this.ContactGroups1 = new HashSet<ContactGroup>();
            this.Functions = new HashSet<Function>();
            this.Groups = new HashSet<Group>();
            this.Invitations = new HashSet<Invitation>();
            this.InvitationLinks = new HashSet<InvitationLink>();
            this.Petitions = new HashSet<Petition>();
            this.Photos = new HashSet<Photo>();
            this.Roles = new HashSet<Role>();
            this.RoleFunctions = new HashSet<RoleFunction>();
            this.RolePeoples = new HashSet<RolePeople>();
        }
    
        public long ID { get; set; }
        public long EntityGroupID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<C_Invitation> C_Invitation { get; set; }
        public virtual ICollection<C_Invitation> C_Invitation1 { get; set; }
        public virtual ICollection<Agreement> Agreements { get; set; }
        public virtual ICollection<Candidate> Candidates { get; set; }
        public virtual ICollection<Candidate> Candidates1 { get; set; }
        public virtual ICollection<Certificate> Certificates { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Contact> Contacts1 { get; set; }
        public virtual ICollection<ContactGroup> ContactGroups { get; set; }
        public virtual ICollection<ContactGroup> ContactGroups1 { get; set; }
        public virtual EntityGroup EntityGroup { get; set; }
        public virtual ICollection<Function> Functions { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<InvitationLink> InvitationLinks { get; set; }
        public virtual ICollection<Petition> Petitions { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<RoleFunction> RoleFunctions { get; set; }
        public virtual ICollection<RolePeople> RolePeoples { get; set; }
    }
}
