//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infopulse.EDemocracy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.ContactGroups = new HashSet<ContactGroup>();
            this.Invitations = new HashSet<Invitation>();
            this.RolePeoples = new HashSet<RolePeople>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long StatusID { get; set; }
    
        public virtual ICollection<ContactGroup> ContactGroups { get; set; }
        public virtual Entity Status { get; set; }
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<RolePeople> RolePeoples { get; set; }
    }
}
