//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infopulse.EDemocracy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvitationLink
    {
        public System.Guid ID { get; set; }
        public long InvitationID { get; set; }
        public long StatusID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public Nullable<long> RunBy { get; set; }
    
        public virtual Entity Status { get; set; }
        public virtual Invitation Invitation { get; set; }
    }
}
