//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infopulse.EDemocracy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public Invitation()
        {
            this.C_Invitation = new HashSet<C_Invitation>();
            this.InvitationLinks = new HashSet<InvitationLink>();
        }
    
        public long ID { get; set; }
        public long GroupID { get; set; }
        public long PersonID { get; set; }
        public long StatusID { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
    
        public virtual ICollection<C_Invitation> C_Invitation { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual Group Group { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<InvitationLink> InvitationLinks { get; set; }
    }
}
