//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infopulse.EDemocracy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Agreements = new HashSet<Agreement>();
            this.AgreementVotes = new HashSet<AgreementVote>();
            this.Candidates = new HashSet<Candidate>();
            this.Certificates = new HashSet<Certificate>();
            this.Contacts = new HashSet<Contact>();
            this.Invitations = new HashSet<Invitation>();
            this.Petitions = new HashSet<Petition>();
            this.PetitionVotes = new HashSet<PetitionVote>();
            this.Photos = new HashSet<Photo>();
            this.RolePeoples = new HashSet<RolePeople>();
        }
    
        public long ID { get; set; }
        public string Login { get; set; }
    
        public virtual ICollection<Agreement> Agreements { get; set; }
        public virtual ICollection<AgreementVote> AgreementVotes { get; set; }
        public virtual ICollection<Candidate> Candidates { get; set; }
        public virtual ICollection<Certificate> Certificates { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<Petition> Petitions { get; set; }
        public virtual ICollection<PetitionVote> PetitionVotes { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<RolePeople> RolePeoples { get; set; }
    }
}
